### PR TITLE
Wrote batch file for exe creation

### PR DESCRIPTION
**Pull request by ElizabethThorner**

### CODE REVIEW

**Comment by mslinger** [comment]
Doesn't work on linux.

**Comment by ElizabethThorner** [comment]
> Doesn't work on linux.

Was there an error message or did the exe just not appear?

**Comment by mslinger** [comment]
Yeah, there's an error about the virtual environment.

**Comment by ElizabethThorner** [comment]
> Yeah, there's an error about the virtual environment. Not sure if it's just my system or whether it works on mac or not.

What's the exact error message? What command did it come after?

**Comment by ElizabethThorner** [comment]
Removed the .sh file and just have the batch file now

**Review by mslinger — APPROVED** [review]

**Pull request merged**
